### ISSUE TITLE
how to solve the 1px border at lib-flexible

### ISSUE THREAD

**Issue by whatwg6** [younth/react-router-redux-mobile-spa#3]
在lib-flexible 中 1px 怎么处理的呀？在iPhone6 p 没变粗,lib-flexible帮忙解决的嘛

**Comment by younth** [comment]
@yxuecheng 不是的。是px2rem插件在编译帮忙处理的。1px不进行rem转化。

**Comment by whatwg6** [comment]
嗯，了解了，不用lib-flexible把他特性给忘了 ，比如 dpr = 2  会把 sacle 改为0.5 所以 边框也自然不需要处理
